spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: porvanivafoo@gmail.com
    password: bank shsx gdxl hwjg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: Internship

  datasource:
    url: jdbc:postgresql://212.132.97.24:5432/pmokhammad
    username: pmokhammad
    password: qfP94j9woo8dISPS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



server:
  port: 8088



